"""Append-only run journal — the spine of the system.

``logs/journal.jsonl`` is simultaneously:

  (a) the judge deliverable — per-iteration hypothesis, diff, metrics, errors,
      recovery events, and intervention flags;
  (b) the agent's own memory — the reflect step reads it to decide what to try next;
  (c) the single source from which ``reports/`` (results table, resource usage,
      interventions summary) are generated by ``scripts/generate_reports.py``.

One append-only JSONL file, one entry per attempted iteration. Everything else is
derived from it. There is never a second source of truth.

This module is intentionally stdlib-only so the journal can be read and written in
any environment, including inside minimal report-generation contexts.

Schema evolution: bump ``SCHEMA_VERSION`` on any change, never rewrite old entries,
and keep ``JournalEntry.from_dict`` able to read every version ever written.
"""

from __future__ import annotations

import dataclasses
import json
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterator, Optional

SCHEMA_VERSION = 2

#: Action types the POLICY may choose from. Mirrors agent/actions/.
POLICY_ACTIONS = ("eda", "feature", "model", "tune", "debug")

#: Entry type for a human intervention. Never proposed by any policy — written only by
#: scripts/log_intervention.py. It is a first-class journal entry because the count of
#: interventions is a judge deliverable (Autonomy, 20%), and a number that cannot be
#: produced from the journal is a number nobody should trust.
INTERVENTION = "intervention"

#: Everything the journal will accept in `action_type`.
ACTION_TYPES = POLICY_ACTIONS + (INTERVENTION,)


@dataclass
class ErrorEvent:
    """One failure inside an iteration, and what the harness did about it.

    Robustness is judged on recovery behaviour, not failure count — every failure
    MUST be recorded together with the recovery taken, even when the iteration was
    ultimately rejected.

    Fields
    ------
    error_type:
        Category of the failure. One of: ``"code_error"`` (generated code raised /
        non-zero exit), ``"timeout"`` (subprocess hit the hard timeout),
        ``"bad_llm_output"`` (unparseable or contract-violating LLM response),
        ``"eval_error"`` (metric computation failed), ``"llm_api_error"``
        (provider failure at the single call site), ``"data_error"`` (bad input).
    message:
        Truncated stderr / exception text. Keep under ~2KB — the journal is read
        back into LLM context by the reflect step.
    recovery:
        Action the harness took: ``"retry"`` (same thing again), ``"reroute"``
        (different action / prompt / branch), ``"revert"`` (workspace rolled back),
        ``"debug_action"`` (a debug iteration was scheduled), ``"abort"`` (the
        iteration was abandoned).
    recovered:
        True if the run continued normally after this event. A final crash of the
        whole run would be the only ``False`` that is also the last entry — the
        loop is designed so that never happens.
    """

    error_type: str
    message: str
    recovery: str
    recovered: bool


@dataclass
class JournalEntry:
    """One attempted iteration of the agent loop.

    Field-by-field contract
    -----------------------
    schema_version:
        ``SCHEMA_VERSION`` at write time. Readers dispatch on it.
    node_id:
        Unique id of this iteration's node in the search tree (short hex string).
        Also keys the diff file, checkpoint directory, and workspace branch names.
    parent_id:
        ``node_id`` of the node this iteration branched from, or ``None`` for the
        root. Parent links make the journal a faithful record of the search tree —
        which mirrors the workspace git commit graph.
    iteration:
        0-based index of the attempt in wall-clock order (the journal is
        append-only, so this equals the line number, but is stored explicitly so
        entries are self-contained).
    timestamp:
        ISO-8601 UTC time the entry was written (end of the iteration).
    action_type:
        One of ``ACTION_TYPES`` — which action module produced this iteration.
    hypothesis:
        The agent's stated reason for trying this, in its own words. This is the
        raw material for the Innovation & Problem Insight score (20%) — never
        leave it empty, even for the dumb random policy ("random baseline action").
    config:
        JSON-serialisable snapshot of the knobs this iteration ran with (model
        params, feature flags, etc.). Whatever is needed to make the iteration
        interpretable without the code diff.
    diff_path:
        Repo-relative path to the ``git format-patch`` output for this iteration
        under ``logs/diffs/``, or ``None`` if no code changed (e.g. pure EDA).
    commit_sha:
        Workspace-repo commit sha if the iteration was accepted and committed,
        else ``None``. Rejected iterations leave no commit (workspace is reverted).
    checkpoint_path:
        Repo-relative path to the saved model checkpoint for this iteration under
        ``checkpoints/``, or ``None``. The validation-best entry's checkpoint is
        the one evaluated on hidden test — losing it loses the submission.
    val_gauc / val_ndcg5:
        VALIDATION metrics from ``eval/scorer.py`` (the vendored official
        ``evaluate.py``), or ``None`` if the iteration failed before evaluation.
        These are always the *valid* split — the loop never scores test (see
        CLAUDE.md > Test-set integrity). ``val_primary`` is derived, not stored,
        so the stored metrics can never disagree with the selection scalar.
    wall_seconds:
        Wall-clock duration of the whole iteration (LLM calls + execution + eval).
    gpu_seconds:
        GPU time consumed by this iteration. 0.0 for CPU-only work (the default —
        LightGBM). Summed across the run for the resource report (15% of score).
    tokens_in / tokens_out:
        LLM tokens consumed by this iteration, summed over every call made through
        ``agent/llm.py`` — including failed calls and retries. The journal total
        must equal the provider-side total; ``agent/llm.py`` being the single call
        site is what makes that auditable.
    stdout_tail:
        Truncated stdout from the pipeline subprocess (schema v2+). This is the
        agent's only window into its own training dynamics: loss curves, epoch
        counts, per-epoch validation, feature shapes. Without it the agent sees
        one number per iteration and cannot distinguish "my hypothesis was wrong"
        from "my SGD did not converge" — in the first live run it abandoned two
        sound ideas (BPR, FM) after undertrained implementations scored badly.
        Fed back into the reflect step by ``agent/memory.py``.
    error_events:
        Every failure within the iteration and its recovery, in order. Empty list
        for a clean iteration.
    accepted:
        True if the critic accepted the iteration (workspace committed), False if
        rejected (workspace reverted). Failed iterations are False.
    intervention:
        True if a human manually intervened in or around this iteration (edited
        code, restarted the run, changed config mid-run, ...). The count of True
        values is a judge deliverable (Autonomy, 20%) — log honestly and
        conservatively: when in doubt, it was an intervention.
    intervention_note:
        What the human did and why, when ``intervention`` is True. ``None`` otherwise.
    """

    node_id: str
    parent_id: Optional[str]
    iteration: int
    timestamp: str
    action_type: str
    hypothesis: str
    config: dict[str, Any]
    diff_path: Optional[str]
    commit_sha: Optional[str]
    checkpoint_path: Optional[str]
    val_gauc: Optional[float]
    val_ndcg5: Optional[float]
    wall_seconds: float
    gpu_seconds: float
    tokens_in: int
    tokens_out: int
    stdout_tail: Optional[str] = None
    error_events: list[ErrorEvent] = field(default_factory=list)
    accepted: bool = False
    intervention: bool = False
    intervention_note: Optional[str] = None
    schema_version: int = SCHEMA_VERSION

    def __post_init__(self) -> None:
        if self.action_type not in ACTION_TYPES:
            raise ValueError(
                f"action_type {self.action_type!r} not in {ACTION_TYPES}"
            )

    @property
    def val_primary(self) -> Optional[float]:
        """``mean(GAUC, nDCG@5)`` — the organisers' primary metric and our selection
        scalar. ``None`` if either metric is missing (a failed iteration).

        Derived, never stored: the absolute-delta score the judges compute is
        ``val_primary - baseline_primary``, and mean-of-per-metric-deltas equals
        delta-of-primary exactly, so this one number drives both convergence and
        checkpoint selection.
        """
        if self.val_gauc is None or self.val_ndcg5 is None:
            return None
        return (self.val_gauc + self.val_ndcg5) / 2.0

    def to_dict(self) -> dict[str, Any]:
        """Plain-dict form, safe for ``json.dumps``."""
        return dataclasses.asdict(self)

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "JournalEntry":
        """Inverse of :meth:`to_dict`. Must accept every schema version ever written.

        v1 entries have no ``stdout_tail``; the field defaults to None, so older
        journals keep loading without migration.
        """
        d = dict(d)
        d["error_events"] = [ErrorEvent(**e) for e in d.get("error_events", [])]
        return cls(**d)


def append_entry(journal_path: str | Path, entry: JournalEntry) -> None:
    """Append one entry as a single JSON line, flushed and fsynced.

    fsync matters: the journal must survive the harness being killed mid-run —
    a torn journal breaks resume, reports, and the judge deliverable at once.
    """
    line = json.dumps(entry.to_dict(), ensure_ascii=False)
    with open(journal_path, "a", encoding="utf-8") as f:
        f.write(line + "\n")
        f.flush()
        os.fsync(f.fileno())


def read_entries(journal_path: str | Path) -> Iterator[JournalEntry]:
    """Yield entries in append order. Skips blank lines; raises on corrupt ones."""
    with open(journal_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            yield JournalEntry.from_dict(json.loads(line))


def load_journal(journal_path: str | Path) -> list[JournalEntry]:
    """Read the whole journal into memory (it is small — one line per iteration)."""
    return list(read_entries(journal_path))
